gpio:
  pin: 4 # pin number to trigger the tts
google:
  auth:
    keyPath: '/home/user/auth.json' # path to the auth key
  tts:
    language: 'cs-CZ' # language code https://cloud.google.com/text-to-speech/docs/voices
realtime:
  url: 'http://my.meteo/realtime.txt' # URL to get the weather from
message:
  template: 'Milovice rádio dobrý den. Čas <#TIME>. Vítr <#WIND>. Dráha v používání <#RWY>. Okruhy <#CIRCUIT>. Teplota <#TEMP>. Základna oblačnosti <#CLOUDBASE>. QNH <#QNH>.'
  timezoneOffset: '+2' # means the time from realtime.txt is UTC+2 (2 hours will be subtracted to get the UTC time), use '0' if no change needed
  wind:
    calm: 'klid' # Wind calm.
    speedUnits: 'uzlů' # Wind speed units
    bearingUnits: 'stupňů' # Wind bearing units
    gust: 'nárazy' # Wind gusts
  rwy:
    - result: '27'        # Runway 27 will be set if the wind bearing is > 180
      condition: '> 180'  # THERE MUST BE A SPACE BETWEEN THE OPERATOR AND THE NUMBER
    - result: '09'        # Runway 09 will be set if the wind bearing is <= 180
      condition: '<= 180' # THERE MUST BE A SPACE BETWEEN THE OPERATOR AND THE NUMBER
  circuits:
    - result: 'levé'        # levé circuits will be set if the wind bearing is > 180
      condition: '> 180'  # THERE MUST BE A SPACE BETWEEN THE OPERATOR AND THE NUMBER
    - result: 'pravé'       # pravé circuits will be set if the wind bearing is <= 180
      condition: '<= 180' # THERE MUST BE A SPACE BETWEEN THE OPERATOR AND THE NUMBER
  temperature:
    units: 'stupňů' # temperature units (degrees, not Celsius or Fahrenheit)
  cloudbase:
    units: 'stop' # cloudbase units
