# This is a basic workflow to help you get started with Actions

name: tests & lint

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_upload:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Build image
        run: docker build -t weather-tts:latest --target production .

      - name: Upload image
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: "weather-tts:latest"

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: [build_and_upload]

    steps:
    - name: Checkout project
      uses: actions/checkout@v2

    - name: Download built docker image
      uses: ishworkh/docker-image-artifact-download@v1
      with:
        image: "weather-tts:latest"

    - name: Run tests
      run: make test

  lint:
    name: Run eslint
    runs-on: ubuntu-latest
    needs: [build_and_upload]

    steps:
    - name: Checkout project
      uses: actions/checkout@v2

    - name: Download built docker image
      uses: ishworkh/docker-image-artifact-download@v1
      with:
        image: "weather-tts:latest"

    - name: Run lint
      run: make lint
